version: "3.9"
services:
  geth-init:
    image: "ethereum/client-go:latest"
    command: --datadir=/data init /genesis.json
    volumes:
      - ./genesis.json:/genesis.json
      - ./data:/data

  geth:
    image: "ethereum/client-go:latest"
    command:
      - --http
      - --http.api=eth,net,web3,personal,miner,txpool,clique,admin
      - --http.addr=0.0.0.0
      - --datadir=data
      - --allow-insecure-unlock
      - --nodiscover
      - --unlock=0x75333f8c0dd26112676597b66a42fb5b5da2b440
      - --password=password.txt
      - --mine
      - --nat="extip:13.213.36.146"
    depends_on:
      geth-init:
        condition: service_completed_successfully
    ports:
      - 8545:8545
    volumes:
      - ./data:/data
      - ./password.txt:/password.txt